//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatLight.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatLight.Core.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TestRun id=&quot;e83f94ca-b0fe-41dd-af9e-9f7adcefe7a0&quot; name=&quot;StatLight TestRun&quot; runUser=&quot;DOMAIN\UserName&quot; xmlns=&quot;http://microsoft.com/schemas/VisualStudio/TeamTest/2010&quot;&gt;
        ///  &lt;TestSettings name=&quot;Local&quot; id=&quot;184c7c57-d71a-480f-9de6-18ff3b15a7ff&quot;&gt;
        ///    &lt;Description&gt;These are default test settings for a local test run.&lt;/Description&gt;
        ///    &lt;Deployment enabled=&quot;false&quot; runDeploymentRoot=&quot;UserName_UserName-LT3 2011-08-23 11_36_44&quot; /&gt;
        ///    &lt;Execution&gt;
        ///      &lt;TestTypeSpecific /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTRX_GeneratedFromRealTest {
            get {
                return ResourceManager.GetString("SampleTRX_GeneratedFromRealTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://microsoft.com/schemas/VisualStudio/TeamTest/2010&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           targetNamespace=&quot;http://microsoft.com/schemas/VisualStudio/TeamTest/2010&quot;
        ///           elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;2010.04&quot;&gt;
        ///  &lt;xs:complexType name=&quot;BaseTestType&quot; abstract=&quot;true&quot;&gt;
        ///    &lt;xs:annotation&gt;
        ///      &lt;xs:documentation&gt;Shared between all test types.&lt;/xs:docu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vstst {
            get {
                return ResourceManager.GetString("vstst", resourceCulture);
            }
        }
    }
}
